<a href="https://colab.research.google.com/github/Ayushi-Sharma19/Python/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Array Manipulation
array = np.array([[1, 2], [3, 4], [5, 6]])

# Transpose
transposed_array = np.transpose(array)
print("Transposed Array:\n", transposed_array)

# Reshape
reshaped_array = np.reshape(array, (2, 3))
print("Reshaped Array:\n", reshaped_array)

# Resize
resized_array = np.resize(array, (3, 4))
print("Resized Array:\n", resized_array)

# Flatten
flattened_array = array.flatten()
print("Flattened Array:\n", flattened_array)

# Create a 2D Array
arravali = np.array(np.random.randint(10, 45, (8, 2)))
print("Defined Array:\n", arravali)
print("Shape of the Array:", arravali.shape)

# Transpose of the Array
nilgiri = np.transpose(arravali)
print("Transpose of the Array:\n", nilgiri)
print("Shape of the Transposed Array:", nilgiri.shape)

# Create a 3D Array
random_3d_array = np.array(np.random.randint(10, 45, (3, 2, 4)))
print("Defined 3D Array:\n", random_3d_array)
print("Shape of the 3D Array:", random_3d_array.shape)

# Transpose of the 3D Array
transposed_3d_array = np.transpose(random_3d_array)
print("Transpose of the 3D Array:\n", transposed_3d_array)
print("Shape of the Transposed 3D Array:", transposed_3d_array.shape)

# Reshape a 2D Array
random_cohort = np.array(np.random.randint(10, 45, (3, 8)))
print("Defined 2D Array:\n", random_cohort)
print("Shape of the 2D Array:", random_cohort.shape)

# Reshape to 3D Array
new_shape = (2, 6, 2)
reshaped_random_cohort = np.reshape(random_cohort, new_shape)
print("Reshaped 3D Array:\n", reshaped_random_cohort)
print("Shape of the Reshaped 3D Array:", reshaped_random_cohort.shape)

# Create a 3D Array
random_3D_cohort = np.array(np.random.randint(10, 45, (3, 6, 2)))
print("Defined 3D Array:\n", random_3D_cohort)
print("Shape of the 3D Array:", random_3D_cohort.shape)

# Reshape the 3D Array
new_shape = (2, -1, 6)
reshaped_random_3D_cohort = np.reshape(random_3D_cohort, new_shape)
print("Reshaped 3D Array:\n", reshaped_random_3D_cohort)
print("Shape of the Reshaped 3D Array:", reshaped_random_3D_cohort.shape)

# Resize a 3D Array
random_3D_cohort = np.array(np.random.randint(10, 45, (2, 4, 6)))
print("Defined 3D Array:\n", random_3D_cohort)
print("Shape of the 3D Array:", random_3D_cohort.shape)

# Resize the 3D Array
new_shape = (2, 3, 6)
resized_random_3D_cohort = np.resize(random_3D_cohort, new_shape)
print("Resized 3D Array:\n", resized_random_3D_cohort)
print("Shape of the Resized 3D Array:", resized_random_3D_cohort.shape)

# Flatten a 3D Array
flattened_3D_array = random_3D_cohort.flatten()
print("Flattened 3D Array:\n", flattened_3D_array)

# Insert, Append, Delete, and Unique Operations
a = np.random.randint(10, 20, (2, 3, 4))
print("Original Array:\n", a)
print("Shape of the Array:", a.shape)

# Insert along axis 0
inserted_array_axis0 = np.insert(a, 1, 100, axis=0)
print("Inserted Array along Axis 0:\n", inserted_array_axis0)

# Insert along axis 1
inserted_array_axis1 = np.insert(a, 0, 50, axis=1)
print("Inserted Array along Axis 1:\n", inserted_array_axis1)

# Insert along axis 2
inserted_array_axis2 = np.insert(a, 0, 200, axis=2)
print("Inserted Array along Axis 2:\n", inserted_array_axis2)

# Append a value to the array
appended_array = np.append(a, 50)
print("Appended Array:\n", appended_array)

# Delete along axis 0
deleted_array_axis0 = np.delete(a, 0, axis=0)
print("Deleted Array along Axis 0:\n", deleted_array_axis0)

# Delete along axis 1
deleted_array_axis1 = np.delete(a, (0, 2), axis=1)
print("Deleted Array along Axis 1:\n", deleted_array_axis1)

# Delete along axis 2
deleted_array_axis2 = np.delete(a, (0, 1), axis=2)
print("Deleted Array along Axis 2:\n", deleted_array_axis2)

# Unique elements in the array
unique_elements = np.unique(a)
print("Unique Elements:\n", unique_elements)

# Basic Operations
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Addition
addition = np.add(a, b)
print("Addition:\n", addition)

# Subtraction
subtraction = np.subtract(a, b)
print("Subtraction:\n", subtraction)

# Multiplication
multiplication = np.multiply(a, b)
print("Multiplication:\n", multiplication)

# Division
division = np.divide(a, b)
print("Division:\n", division)

# Sum of items in an array
sum_array = np.sum(a)
print("Sum of Array:\n", sum_array)

# Minimum of items in an array
min_array = np.min(a)
print("Minimum of Array:\n", min_array)

# Maximum of items in an array
max_array = np.max(a)
print("Maximum of Array:\n", max_array)

# Mean of items in an array
mean_array = np.mean(a)
print("Mean of Array:\n", mean_array)

# Sorting an array
sorted_array = np.sort(a)
print("Sorted Array:\n", sorted_array)

Transposed Array:
 [[1 3 5]
 [2 4 6]]
Reshaped Array:
 [[1 2 3]
 [4 5 6]]
Resized Array:
 [[1 2 3 4]
 [5 6 1 2]
 [3 4 5 6]]
Flattened Array:
 [1 2 3 4 5 6]
Defined Array:
 [[32 23]
 [23 20]
 [36 34]
 [28 31]
 [38 43]
 [12 20]
 [44 34]
 [24 26]]
Shape of the Array: (8, 2)
Transpose of the Array:
 [[32 23 36 28 38 12 44 24]
 [23 20 34 31 43 20 34 26]]
Shape of the Transposed Array: (2, 8)
Defined 3D Array:
 [[[13 34 10 34]
  [27 38 37 16]]

 [[40 37 36 25]
  [37 31 22 12]]

 [[33 12 12 44]
  [36 13 18 42]]]
Shape of the 3D Array: (3, 2, 4)
Transpose of the 3D Array:
 [[[13 40 33]
  [27 37 36]]

 [[34 37 12]
  [38 31 13]]

 [[10 36 12]
  [37 22 18]]

 [[34 25 44]
  [16 12 42]]]
Shape of the Transposed 3D Array: (4, 2, 3)
Defined 2D Array:
 [[30 14 34 43 21 36 41 41]
 [14 11 37 25 21 21 36 30]
 [42 36 41 29 24 15 21 23]]
Shape of the 2D Array: (3, 8)
Reshaped 3D Array:
 [[[30 14]
  [34 43]
  [21 36]
  [41 41]
  [14 11]
  [37 25]]

 [[21 21]
  [36 30]
  [42 36]
  [41 29]
  [24 15]
  [21 23]